
[window]
decorations = "none"
dynamic_title = true

[window.padding]
x = 10
y = 10

[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/gruvbox.toml",
    "~/.config/alacritty/jet_brains_mono.toml"
]
