#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor DP1 -d 1 2 3 4 5 6 7 8 9 10

for m in $(bspc query -M --names); do
    bspc monitor "$m" -d 1 2 3 4 5 6 7 8 9 10
done

bspc config border_width         	4
bspc config window_gap          	20

bspc config normal_border_color "#282828"
bspc config active_border_color "#8ec07c"
bspc config focused_border_color "#8ec07c"

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true 
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true
bspc config single_monocle 		true

$HOME/.config/polybar/launch.sh
